# Generated by Django 5.2.7 on 2025-11-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_delete_login_remove_signup_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='balance',
            field=models.TextField(default='0.00'),
        ),
    ]
