# Generated by Django 5.2.7 on 2025-11-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.TextField(),
        ),
    ]
