# Generated by Django 5.2.7 on 2025-12-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
